In [10]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml

data = fetch_openml('mnist_784', version=1, return_X_y=True, as_frame=True)

data

kolone = ['y']
kolone.extend('x'+str(i+1) for i in range(784))

kolone[:10]

data = pd.concat((data[1], data[0]), axis = 1)

data.columns = kolone

data

datatrain = data.sample(50000, random_state=42)
datadev = data.drop(index = datatrain.index).sample(10000, random_state=42)
datatest = data.drop(index = datatrain.index,).drop(index = datadev.index)
print(len(set(datatrain.index) | set(datadev.index) | set(datatest.index)))

70000

In [11]:
datatrain

,y,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x775,x776,x777,x778,x779,x780,x781,x782,x783,x784
46730,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48393,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41416,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34506,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43725,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30085,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57551,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
61640,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3569,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39305,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0